### ISSUE TITLE
Configuring docker-surfshark to use Dante instead of LAN_NETWORK doesn't work

### ISSUE THREAD

**Issue by MatthewUpdike** [ilteoood/docker-surfshark#23]
The docker image works perfectly fine and I'm able to make `curl` requests inside the container. I decided to replace LAN_NETWORK with SOCKD_WORKERS for the configuration of the socks5 server via Dante, but it's causing me some troubles.

The **sockd.conf** files looks like this: (I also tried `external: tun0`)

```
debug: 0
logoutput: stderr
# internal: 0.0.0.0 port = 1080
internal: eth0 port = 1080
internal: lo port = 1080
external: tun0
socksmethod: username none
clientmethod: none
user.privileged: root
user.unprivileged: nobody

client pass {
    from: 0.0.0.0/0 port 1-65535 to: 0.0.0.0/0
    log: error
}

socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    #socksmethod: username
    log: error
}
```

The **docker-compose.yml** files stays relatively the same:

```
version: "3"

services: 
    surfshark:
        image: ilteoood/docker-surfshark
        container_name: surfshark
        environment: 
            - SURFSHARK_USER=SURFSHARK_USER
            - SURFSHARK_PASSWORD=SURFSHARK_PASSWORD
            - SURFSHARK_COUNTRY=de
            - SURFSHARK_CITY=
            - CONNECTION_TYPE=tcp
            - SOCKD_WORKERS=10
            - OPENVPN_OPTS=
        cap_add: 
            - NET_ADMIN
        devices:
            - /dev/net/tun
        ports:
            - 1080:1080
        dns:
            - 1.1.1.1
```

The commands inside **startup.sh** are all the same except the last line:

```
openvpn --config $VPN_FILE --auth-user-pass vpn-auth.txt --mute-replay-warnings \
        --script-security 2 --up '/bin/sh -c sockd -N $SOCKD_WORKERS' $OPENVPN_OPTS
```

Eventually, when I make a request from my host (outside of the container) using `curl` like either so:

`curl -x socks5h://127.0.0.1:1080 https://ipinfo.io`

or so:

`curl --socks5-hostname 127.0.0.1:1080 https://ipinfo.io`

The connection fails, and I get the same error all the time:

**Host**:

```
curl: (7) Can't complete SOCKS5 connection to 0.0.0.0:0. (6)
```

**Container**:
```
sockd[18]: info: Dante/server[1/1] v1.4.2 running
sockd[38]: info: block(1): tcp/accept ]: 192.168.16.1.58610 192.168.16.2.1080: error after reading 1 byte in 0 seconds: unknown SOCKS version 71 in client request
```

After altering stuff I don't remember correctly what it was inside **sockd.conf**, the error changed to:

`curl: (7) Can't complete SOCKS5 connection to ipinfo.io:443. (4)`

I tried using [SurfShark's cli tool](https://surfshark.com/download/linux) but it's completely broken plus it's not alpine compatible. It may be worth mentioning that I tried something similar with [protonVPN's cli tool](https://protonvpn.com/support/linux-vpn-tool/) which is python3 compatible and actually works, it automatically creates a new interface **proton0** which can be set inside **sockd.conf**  as:

`external: proton0`

**Do you know how to make it work with OpenVPN?**
