### ISSUE TITLE
Cannot access web UI of Deluge + oddities

### ISSUE THREAD

**Issue by themaster567** [ilteoood/docker-surfshark#32]
I am using the latest version and have checked and followed the advice you've given in various issue posts to the best of my ability. Here are the relevant parts of my docker compose stack(credentials censored):
```
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /volume1/docker/deluge/config:/config
      - /mnt/15226186-6020-4107-81c5-aa6f56488f17/torrents:/downloads
    depends_on: 
      - surfshark
    network_mode: service:surfshark
    restart: unless-stopped 
```

```
  surfshark:
    image: ilteoood/docker-surfshark
    container_name: surfshark
    environment: 
      - SURFSHARK_USER=***
      - SURFSHARK_PASSWORD=***
      - SURFSHARK_COUNTRY=us
    cap_add: 
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    dns:
      - 1.1.1.1
```

I've confirmed that Surfshark is connecting properly, Portainer says that Deluge is in the correct network, but but I can't connect to the web UI when I try. When I first exec into Deluge's container and curl ipinfo.io, I got told that I was being rate limited after my previous attempts. The weird part is that after that, not a single one of my curls worked for any other site. I don't get an error, I get nothing at all.

```
root@6d3d4ebe2579:/# curl ipinfo.io
{
  "status": 429,
  "error": {
    "title": "Rate limit exceeded",
    "message": "You've hit the daily limit for the unauthenticated API.  Create an API access token by signing up to get 50k req/month."
  }
}root@6d3d4ebe2579:/# curl ipchicken.com
root@6d3d4ebe2579:/# curl ipapi.co
root@6d3d4ebe2579:/# curl ipwhois.io
root@6d3d4ebe2579:/# curl ipapi.co
root@6d3d4ebe2579:/# curl https://ipapi.co/8.8.8.8/country/
```

So now I'm just completely lost.
