### ISSUE TITLE
no access on LAN

### ISSUE THREAD

**Issue by millsjoe** [ilteoood/docker-surfshark#55]
```
version: "2"
services:

  surfshark:
    image: ilteoood/docker-surfshark
    container_name: surfshark
    environment:
       - SURFSHARK_USER=<username>
       - SURFSHARK_PASSWORD=<password>
       - SURFSHARK_COUNTRY=it
       - SURFSHARK_CITY=mil
       - CONNECTION_TYPE=udp
       - LAN_NETWORK=192.168.0.45
    cap_add:
        - NET_ADMIN
    devices:
        - /dev/net/tun
    ports:
        - 9091:9091 # plus some others but none are accessible
    restart: unless-stopped
    dns:
        - 1.1.1.1
```
hi im trying to use some containers that go via your image and can't seem to access them from another device on my network. am i configuring the `LAN_NETWORK` correctly where `192.168.0.45` is the device running containers? (tried `192.168.0.45/24` too)

**Comment by ilteoood** [comment]
Can you paste the full compose file with your services definition?

**Comment by millsjoe** [comment]
```
version: "2"
services:
  surfshark:
    image: ilteoood/docker-surfshark
    container_name: surfshark
    environment:
       - SURFSHARK_USER=<username> # redacted for this
       - SURFSHARK_PASSWORD=<password> # redacted for this
       - SURFSHARK_COUNTRY=it
       - SURFSHARK_CITY=mil
       - CONNECTION_TYPE=udp
       - LAN_NETWORK=192.168.0.45
    cap_add:
        - NET_ADMIN
    devices:
        - /dev/net/tun
    ports:
        - 8112:8112
        - 8989:8989
        - 32400:32400
        - 6881:6881
        - 6881:6881/udp
        - 7878:7878
        - 3579:3579
        - 9117:9117
    restart: unless-stopped
    dns:
        - 1.1.1.1
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=0
      - PGID=0
      - VERSION=docker
    volumes:
      - ~/docker-services/plex/config:/config
      - /mnt:/mnt
    depends_on:
       - surfshark
    network_mode: service:surfshark
    #ports:
     # - 32400:32400
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:version-3.0.8.1507
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=GMT
    volumes:
      - ~/docker-services/sonarr/config:/config
    depends_on:
      - surfshark
    network_mode: service:surfshark
    #ports:
     # - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=GMT
    volumes:
      - ~/docker-services/radarr/config:/config
    depends_on:
      - surfshark
    network_mode: service:surfshark
    #ports:
     # - 7878:7878
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - ~/docker-services/deluge/config:/config
    depends_on:
      - surfshark
    network_mode: service:surfshark
    #ports:
     # - 8112:8112
      #- 6881:6881
      #- 6881:6881/udp
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - ~/docker-services/jackett/config:/config
    depends_on:
      - surfshark
    network_mode: service:surfshark
    #ports:
     # - 9117:9117
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=0
      - PGID=0
      - TZ=PST
      - BASE_URL=/ombi #optional
    volumes:
      - ~/docker-services/ombi/config:/config
    depends_on:
      - surfshark
    network_mode: service:surfshark
    #ports:
     # - 3579:3579
    restart: unless-stopped
```

sure thing, i could probably pull things like plex out of surfshark but would be great if i could get it all running through it. I can access all these on the host device using like `localhost:9117` but ideally want to be able to do from a different device on my network. ports are commented out for my sanity of whats what
