### ISSUE TITLE
Can't access from another container by service name.

### ISSUE THREAD

**Issue by devXpro** [ilteoood/docker-surfshark#58]
I have this config:
```
version: '3'
services:
  bot:
    restart: always
    build: .
  chrome:
    image: browserless/chrome
    network_mode: service:surfshark
  surfshark:
    image: ilteoood/docker-surfshark
    container_name: surfshark
    environment:
      - SURFSHARK_USER=$SURFSHARK_USER
      - SURFSHARK_PASSWORD=$SURFSHARK_PASSWORD
      - SURFSHARK_COUNTRY=es
      - CONNECTION_TYPE=udp
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    dns:
      - 1.1.1.1
```
I want to access the host 'chrome' from the 'bot' container using the service name, but it's not working. How can I fix this?

**Comment by ilteoood** [comment]
Hi @devXpro,
you should define the `LAN_NETWORK` parameter:
![image](https://user-images.githubusercontent.com/6383527/231982094-c7fc76cd-3c4e-495d-8365-3ffae9390b90.png)

**Comment by devXpro** [comment]
@ilteoood I already tried that and it didn't help.
```
version: '3'
services:
  bot:
    restart: always
    build: .
  chrome:
    image: browserless/chrome
    network_mode: service:surfshark
  surfshark:
    image: ilteoood/docker-surfshark
    container_name: surfshark
    environment:
      - SURFSHARK_USER=$SURFSHARK_USER
      - SURFSHARK_PASSWORD=$SURFSHARK_PASSWORD
      - SURFSHARK_COUNTRY=es
      - CONNECTION_TYPE=udp
      - LAN_NETWORK=192.168.0.0/24
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    dns:
      - 1.1.1.1
```
I go inside the bot container and run `wget http://chrome` there, I get an error wget: bad address 'chrome'
