### ISSUE TITLE
AUTH: Received control message: AUTH_FAILED

### ISSUE THREAD

**Issue by abodilsen** [ilteoood/docker-surfshark#80]
Hello,

I'm encountering an issue with the Surfshark container while using the ilteoood/docker-surfshark image. Here is my docker-compose.yml configuration:

```
version: "2"

services: 
    surfshark:
        image: ilteoood/docker-surfshark
        container_name: surfshark
        environment: 
            - SURFSHARK_USER=demoemail@example.com
            - SURFSHARK_PASSWORD=DemoPassword.123
            - SURFSHARK_COUNTRY=it
            - SURFSHARK_CITY=mil
            - CONNECTION_TYPE=udp
            - LAN_NETWORK=
        cap_add: 
            - NET_ADMIN
        devices:
            - /dev/net/tun
        ports:
            - 1080:1080
            - 9091:9091
        restart: unless-stopped
        dns:
            - 1.1.1.1
    service_test:
        image: byrnedo/alpine-curl
        container_name: alpine
        command: -L 'https://ipinfo.io'
        depends_on: 
            - surfshark
        network_mode: service:surfshark
        restart: always
    transmission:
        image: linuxserver/transmission
        container_name: transmission
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Rome
        network_mode: service:surfshark

```
(Note: The SURFSHARK_USER and SURFSHARK_PASSWORD values provided above are placeholders. For testing purposes, I've reset my Surfshark password to include only letters, numbers, and a single period.)

Steps to reproduce:

Navigate to the directory containing the docker-compose.yml file.
Run **docker-compose -f docker-compose.yml up -d**.
When I check the logs using **docker logs surfshark**, I receive the following output:

Chose: it-mil.prod.surfshark.com_udp.ovpn
...
2023-10-18 22:06:08 **AUTH: Received control message: AUTH_FAILED**
2023-10-18 22:06:08 SIGTERM[soft,auth-failure] received, process exiting
...
Firewall is active and enabled on system startup

This suggests that there's an authentication failure. I have sucssfully tried to login to surfshark with the credentials used in the compose.yml. Do you have any insights or recommendations on how to resolve this? Your assistance would be greatly appreciated.

Thank you!
