### ISSUE TITLE
Sock5 Fails

### ISSUE THREAD

**Issue by josearodrigueze** [ilteoood/docker-surfshark#82]
Hello, I tried to activate the socks5 service but it doesn't work. For now I want to activate this locally so that I can test connecting other services to it and then go to a server in the cloud. This is my configuration:

```
version: "3"

services: 
  vpn:
    image: ilteoood/docker-surfshark
    container_name: vpn
    # platform: linux/amd64
    environment: 
      - SURFSHARK_USER= YOUR_SURFSHARK_USER
      - SURFSHARK_PASSWORD= YOUR_SURFSHARK_PASS
      - SURFSHARK_COUNTRY=it
      - SURFSHARK_CITY=mil
      - CONNECTION_TYPE=udp
      - LAN_NETWORK=192.168.0.0/24
    cap_add: 
      - NET_ADMIN 
    devices:
      - /dev/net/tun
    ports:
      - 1080:1080 #if you want to use the socks5 server
    restart: unless-stopped
    dns:
      - 1.1.1.1
```

When I run `curl -v --socks5 127.0.0.1:1081 http://myexternalip.com/raw`

It doesn't work and the result is:
```
❯ curl -s -v --socks5 127.0.0.1:1080 http://myexternalip.com/raw
*   Trying 127.0.0.1:1080...
* Connected to 127.0.0.1 (127.0.0.1) port 1080
* Recv failure: Connection reset by peer
* SOCKS4: Failed receiving initial SOCKS5 response: Failure when receiving data from the peer
* Closing connection
```

I followed this other [issue](https://github.com/ilteoood/docker-surfshark/issues/60) but it didn't work for me.

logs for the running container:
![image](https://github.com/ilteoood/docker-surfshark/assets/7081637/db6053d7-a511-4f41-bc62-a68756626322)

I hope you can help me
Thank you
