### ISSUE TITLE
SOCKS5 is it even working anymore?

### ISSUE THREAD

**Issue by kanintesova** [ilteoood/docker-surfshark#96]
I never had any problems with it until I updated the container.

I read that we now have to set a flag to enable it in ENV.

But I only get a Failed to connect to 192.168.1.xxx port 1080 after 0 ms: Connection refused.

Settings in compose are as:

```
services:
  surfshark:
    image: ilteoood/docker-surfshark
    container_name: surfshark
    environment:
      - SURFSHARK_USER=xxxxx
      - SURFSHARK_PASSWORD=xxxxx
      - SURFSHARK_COUNTRY=xx
      - CONNECTION_TYPE=tcp
      - ENABLE_KILL_SWITCH=yes
      - ENABLE_SOCKS_SERVER=yes
      - LAN_NETWORK=192.168.1.0/24
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 1080:1080 # if you want to use the socks5 server
      - 9091:9091 # we open port 9091 for Transmission
    restart: unless-stopped
    dns:
      - 1.1.1.1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9091/transmission/web/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - surfshark-vpn
```

I have not really changed anything but it all seems very broken right now.
