### ISSUE TITLE
Does Killswitch not work or did I wrongly configure?

### ISSUE THREAD

**Issue by Huddling1705** [ilteoood/docker-surfshark#99]
I more or less replicated your config for vpn-testing and when I look at the logs of vpntest, it shows that it is able to connect using my non vpn-ed connection (censored one with exact location/ starting with 84.) before the VPN connection (non-censored one starting with 37.) is established.

Did I configure anything wrong or might there be a problem with the killswitch?

(Yes, I tested without the _ENABLE_KILL_SWITCH_ variable, as this is supposed to be on by default. _true_ was the value I found in the source code, so I put it to be able to remember that this container supports killswitch)

**docker-compose.yml**
```
services:
 
    surfshark:
        image: ilteoood/docker-surfshark
        container_name: surfshark
        environment: 
            - SURFSHARK_USER=myusername
            - SURFSHARK_PASSWORD=mypassword
            - SURFSHARK_COUNTRY=de
            - SURFSHARK_CITY=ber
            - CONNECTION_TYPE=udp
            - ENABLE_KILL_SWITCH=true
        cap_add: 
            - NET_ADMIN
        devices:
            - /dev/net/tun
        restart: unless-stopped
        dns:
            - 1.1.1.1


    vpntest:
        image: byrnedo/alpine-curl
        container_name: vpntest
        command: -L 'https://ipinfo.io'
        depends_on: 
            - surfshark
        network_mode: service:surfshark
        restart: always
```

**console output**
```
myusername@devicename:~$ sudo docker compose up -d
[+] Running 4/4
 ✔ Network myusername_default  Created                                                                                                                                                     0.1s
 ✔ Container samba        Started                                                                                                                                                     0.3s
 ✔ Container surfshark    Started                                                                                                                                                     0.3s
 ✔ Container vpntest      Started                                                                                                                                                     0.3s
myusername@devicename:~$ sudo docker logs vpntest
{
  "ip": "84.xxx.xxx.xxx",
  "hostname": "xxx.dip0.t-ipconnect.de",
  "city": "cityname",
  "region": "regionname",
  "country": "DE",
  "loc": "coordinates",
  "org": "ISPs name",
  "postal": "ZIP code",
  "timezone": "Europe/Berlin",
  "readme": "https://ipinfo.io/missingauth"
  
[ 2 more times the same log]

{
  "ip": "37.120.217.xxx",
  "city": "Frankfurt am Main",
  "region": "Hesse",
  "country": "DE",
  "loc": "50.1155,8.6842",
  "org": "AS9009 M247 Europe SRL",
  "postal": "60306",
  "timezone": "Europe/Berlin",
  "readme": "https://ipinfo.io/missingauth"
[same log follows from now on]
```
